[package]
name = "wifi-qr"
version = "0.1.1"
description = "A small Windows utiliy to show a QR code for the stored WiFi connections."
license = "MIT"
edition = "2021"

[profile.release]
panic = "abort"   # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
strip = true      # Remove debug symbols

[build-dependencies]
winres = "0.1"

[dependencies]
eframe = "0.27"
egui_extras = { version = "0.27", features = ["all_loaders"] }
image = { version = "0.24", features = ["png"] }
qrcode-generator = "4.1"
raw-window-handle = "0.6"
window-vibrancy = "0.5"
windows-sys = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_UI_Controls",
] }
