[package]
name = "wifi-qr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com//emilk/egui", rev = "9478e50d012c5138551c38cbee16b07bc1fcf283" }
image = "0.24.6"
qrcode-generator = "4.1.8"
raw-window-handle = "0.5.2"
window-shadows = "0.2"
window-vibrancy = "0.4"
windows-sys = { version = "0.48.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_UI_Controls",
] }
